"""Access to the bundled Amharic frequency wordlist.

The list is generated by ``tools/build_lexicon.py`` from public corpora and shipped
gzipped so the app needs no network on first run. If it is missing — a source checkout
that has not run the builder — callers fall back to the hand-written seed list, which is
enough to be useful but will flag a lot of ordinary inflection.
"""

from __future__ import annotations

import gzip
from collections.abc import Iterator
from pathlib import Path

WORDLIST = Path(__file__).with_name("amharic_wordlist.txt.gz")


def available() -> bool:
    return WORDLIST.exists()


def entries(path: Path | None = None) -> Iterator[tuple[str, int]]:
    """Yield ``(surface, frequency)`` in descending frequency order.

    Streamed rather than returned as a list: the file holds several hundred thousand
    entries and the caller writes them straight into SQLite in chunks.
    """
    target = path or WORDLIST
    if not target.exists():
        return
    with gzip.open(target, "rt", encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            surface, _, freq = line.rstrip("\n").partition("\t")
            if not surface:
                continue
            try:
                yield surface, int(freq)
            except ValueError:
                yield surface, 1


def count(path: Path | None = None) -> int:
    return sum(1 for _ in entries(path))
